services:
  ubuntu1:
    image: ubuntu:22
    container_name: ubuntu1
    tty: true
    command: sleep infinity # Mantiene el contenedor en ejecucion

  ubuntu2:
    image: ubuntu:22
    container_name: ubuntu2
    tty: true
    command: sleep infinity # Mantiene el contenedor en ejecucion
